### ISSUE TITLE
ERROR in The target entry-point "angular-cropperjs" has missing dependencies

### ISSUE THREAD

**Issue by vishalsinghpoker** [matheusdavidson/angular-cropperjs#62]
While using this plugin showing below error in my angular 10 project.
ERROR in The target entry-point "angular-cropperjs" has missing dependencies:
 - @angular/core
 - cropperjs
 - @angular/common
Using lastets config for angular 10

**Comment by ayush-successive** [comment]
Any updates on this issue? I'm facing the same error. I have recently upgraded my project from Angular 6 to 13 and, since then the plugin has started giving this error. Here are some logs of the error.

> (node:3288) UnhandledPromiseRejectionWarning: Error: The target entry-point "angular-cropperjs" has missing dependencies:
>  - cropperjs
> 
>     at TargetedEntryPointFinder.findEntryPoints (file:///D:/Projects/Git/.../.../ClientApp/node_modules/@angular/compiler-cli/bundles/chunk-K5FPDA5B.js:941:13)
>     at file:///D:/Projects/Git/.../.../ClientApp/node_modules/@angular/compiler-cli/bundles/chunk-K5FPDA5B.js:1264:33
>     at SingleProcessExecutorSync.doExecute (file:///D:/Projects/Git/.../.../ClientApp/node_modules/@angular/compiler-cli/bundles/chunk-K5FPDA5B.js:1573:23)
>     at file:///D:/Projects/Git/.../.../ClientApp/node_modules/@angular/compiler-cli/bundles/chunk-K5FPDA5B.js:1594:35
>     at SyncLocker.lock (file:///D:/Projects/Git/.../.../ClientApp/node_modules/@angular/compiler-cli/bundles/chunk-K5FPDA5B.js:1765:14)    
>     at SingleProcessExecutorSync.execute (file:///D:/Projects/Git/.../.../ClientApp/node_modules/@angular/compiler-cli/bundles/chunk-K5FPDA5B.js:1594:19)
>     at mainNgcc (file:///D:/Projects/Git/.../.../ClientApp/node_modules/@angular/compiler-cli/bundles/chunk-K5FPDA5B.js:2103:19)
>     at Module.process (file:///D:/Projects/Git/.../.../ClientApp/node_modules/@angular/compiler-cli/bundles/ngcc/index.js:34:10)
>     at NgccProcessor.processModule (D:\Projects\Git\...\...\ClientApp\node_modules\@ngtools\webpack\src\ngcc_processor.js:175:27)
>     at D:\Projects\Git\...\...\ClientApp\node_modules\@ngtools\webpack\src\ivy\host.js:146:18
>     at D:\Projects\Git\...\...\ClientApp\node_modules\@ngtools\webpack\src\ivy\host.js:76:24
>     at Array.map (<anonymous>)
>     at Object.host.resolveModuleNames (D:\Projects\Git\...\...\ClientApp\node_modules\@ngtools\webpack\src\ivy\host.js:74:32)
>     at actualResolveModuleNamesWorker (D:\Projects\Git\...\...\ClientApp\node_modules\typescript\lib\typescript.js:113796:153)
>     at resolveModuleNamesWorker (D:\Projects\Git\...\...\ClientApp\node_modules\typescript\lib\typescript.js:114065:26)
>     at resolveModuleNamesReusingOldState (D:\Projects\Git\...\...\ClientApp\node_modules\typescript\lib\typescript.js:114161:24)
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:3288) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:3288) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
>
